### ISSUE TITLE
$ParseUtil::Domain::VERSION == undef

### ISSUE THREAD

**Issue by skington** [heytrav/ParseUtil-Domain#16]
Commit https://github.com/heytrav/ParseUtil-Domain/commit/1d8b5c026582f3971377ed8ab14ea380d20342c0 removed the manually-generated $VERSION but failed to add an automatically-generated one. As such, our code at $WORK looks for the version of ParseUtil::Domain, sees undef, thinks "that's not good enough", downloads the latest version of the module, then looks at the version, sees undef, thinks "that's not good enough" etc.

**Comment by heytrav** [comment]
@skington Thanks for making me aware of this. Looks like I forgot a directive when I switched over to `Dist::Zilla`.

I just pushed a new version up to CPAN. Please let me know if you have any more problems with this.

**Comment by skington** [comment]
Works now, thanks :-) .
