### ISSUE TITLE
Avoid use utf8::all

### ISSUE THREAD

**Issue by ribugent** [heytrav/ParseUtil-Domain#7]
According to utf8::all [documentation](https://metacpan.org/pod/utf8::all) changes how all filehandles are opened.

On my particular case using your module since 2.35 version is breaking an old cgi app on my company.

IMHO changing some perl default behaviours including a module is very dangerious.

I'm not sure if you really need it, I did a quick test removing it and all your tests were successfull... 

Thanks

**Comment by heytrav** [comment]
Thanks a lot! I'll check the tests out to confirm that is indeed the case.

**Comment by heytrav** [comment]
#11

**Comment by heytrav** [comment]
`utf8::all` has been removed.
